version: '3.8'
services:
  app:
    image: cln-at-sample-go:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      GIN_MODE: debug
  database:
    image: docker-mysql-8-0:latest
    container_name: my-cont
    hostname: test-host
    ports:
      - 3306:3306
