CREATE TABLE users (
    ID         SERIAL PRIMARY KEY,
    NAME       VARCHAR(256) NOT NULL,
    ACTIVE     INT DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT (CURRENT_DATE),
    UPDATED_AT TIMESTAMP DEFAULT (CURRENT_DATE),
    REMARK     VARCHAR(1024)
);

INSERT INTO users(NAME, ACTIVE, CREATED_AT, UPDATED_AT, REMARK)VALUES('tarou', 1, curdate(), curdate(), 'remark');
INSERT INTO users(NAME, ACTIVE, CREATED_AT, UPDATED_AT, REMARK)VALUES('hanako', 0, curdate(), curdate(), 'remark222');
